name: 'Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: 'actions/checkout@v2'
      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
